# Generated by Django 2.2.10 on 2020-09-06 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dependents",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dependents", models.CharField(default="1", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("education", models.CharField(default="Graduate", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(default="Male", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Married",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("married", models.CharField(default="Yes", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Property_Area",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_area", models.CharField(default="Rural", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Self_Employed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eelf_employed", models.CharField(default="No", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "application_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "applicantincome",
                    models.CharField(default="Married-civ-spouse", max_length=100),
                ),
                (
                    "cooapplicantincome",
                    models.CharField(default="Craft-repair", max_length=100),
                ),
                ("loanamount", models.CharField(default="Husband", max_length=100)),
                ("loan_amount_term", models.CharField(default="White", max_length=100)),
                ("credit_history", models.CharField(default="Male", max_length=100)),
                (
                    "dependents",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loan.Dependents",
                    ),
                ),
                (
                    "education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loan.Education"
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loan.Gender"
                    ),
                ),
                (
                    "married",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loan.Married"
                    ),
                ),
                (
                    "property_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loan.Property_Area",
                    ),
                ),
                (
                    "self_employed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loan.Self_Employed",
                    ),
                ),
            ],
        ),
    ]
