# Generated by Django 2.2.10 on 2020-09-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="self_employed",
            old_name="eelf_employed",
            new_name="self_employed",
        ),
    ]
