# Generated by Django 2.2.10 on 2020-09-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0003_auto_20200907_1224"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="applicantincome",
            field=models.CharField(default=5000, max_length=100),
        ),
        migrations.AlterField(
            model_name="loan",
            name="cooapplicantincome",
            field=models.CharField(default=10000, max_length=100),
        ),
        migrations.AlterField(
            model_name="loan",
            name="credit_history",
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_amount_term",
            field=models.CharField(default=360, max_length=100),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loanamount",
            field=models.CharField(default=10000, max_length=100),
        ),
    ]
