# Generated by Django 2.2.10 on 2020-09-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0005_employee"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
