# Generated by Django 2.2.10 on 2020-10-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0006_delete_employee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="cooapplicantincome",
            new_name="coapplicantincome",
        ),
        migrations.RenameField(
            model_name="loan",
            old_name="application_number",
            new_name="loan_id",
        ),
    ]
