from django.db import models
from django.urls import reverse

# Create your models here.


class Binary_Data(models.Model):
    binary_data = models.CharField(max_length=100, default=1)

    def __str__(self):
        return "{}".format(self.binary_data)


class Bima(models.Model):
    id = models.IntegerField(primary_key=True)
    product_info_1 = models.IntegerField(primary_key=False, default=1)
    product_info_2 = models.CharField(max_length=100, default=1)
    product_info_3 = models.IntegerField(primary_key=False, default=1)
    product_info_4 = models.CharField(max_length=100, default=1)
    product_info_5 = models.IntegerField(primary_key=False, default=1)
    product_info_6 = models.IntegerField(primary_key=False, default=1)
    product_info_7 = models.IntegerField(primary_key=False, default=1)
    ins_age = models.CharField(max_length=100, default=1)
    ht = models.CharField(max_length=100, default=1)
    wt = models.CharField(max_length=100, default=1)
    bmi = models.CharField(max_length=100, default=1)
    employment_info_1 = models.CharField(max_length=100, default=1)
    employment_info_2 = models.IntegerField(primary_key=False, default=1)
    employment_info_3 = models.IntegerField(primary_key=False, default=1)
    employment_info_4 = models.CharField(max_length=100, default=1)
    employment_info_5 = models.IntegerField(primary_key=False, default=1)
    employment_info_6 = models.CharField(max_length=100, default=1)
    insuredinfo_1 = models.IntegerField(primary_key=False, default=1)
    insuredinfo_2 = models.IntegerField(primary_key=False, default=1)
    insuredinfo_3 = models.IntegerField(primary_key=False, default=1)
    insuredinfo_4 = models.IntegerField(primary_key=False, default=1)
    insuredinfo_5 = models.IntegerField(primary_key=False, default=1)
    insuredinfo_6 = models.IntegerField(primary_key=False, default=1)
    insuredinfo_7 = models.IntegerField(primary_key=False, default=1)
    insurance_history_1 = models.IntegerField(primary_key=False, default=1)
    insurance_history_2 = models.IntegerField(primary_key=False, default=1)
    insurance_history_3 = models.IntegerField(primary_key=False, default=1)
    insurance_history_4 = models.IntegerField(primary_key=False, default=1)
    insurance_history_5 = models.CharField(max_length=100, default=1)
    insurance_history_7 = models.IntegerField(primary_key=False, default=1)
    insurance_history_8 = models.IntegerField(primary_key=False, default=1)
    insurance_history_9 = models.IntegerField(primary_key=False, default=1)
    family_hist_1 = models.IntegerField(primary_key=False, default=1)
    family_hist_2 = models.CharField(max_length=100, default=1)
    family_hist_3 = models.CharField(max_length=100, default=1)
    family_hist_4 = models.CharField(max_length=100, default=1)
    family_hist_5 = models.CharField(max_length=100, default=1)
    medical_history_1 = models.CharField(max_length=100, default=1)
    medical_history_2 = models.IntegerField(primary_key=False, default=1)
    medical_history_3 = models.IntegerField(primary_key=False, default=1)
    medical_history_4 = models.IntegerField(primary_key=False, default=1)
    medical_history_5 = models.IntegerField(primary_key=False, default=1)
    medical_history_6 = models.IntegerField(primary_key=False, default=1)
    medical_history_7 = models.IntegerField(primary_key=False, default=1)
    medical_history_8 = models.IntegerField(primary_key=False, default=1)
    medical_history_9 = models.IntegerField(primary_key=False, default=1)
    medical_history_10 = models.CharField(max_length=100, default=1)
    medical_history_11 = models.IntegerField(primary_key=False, default=1)
    medical_history_12 = models.IntegerField(primary_key=False, default=1)
    medical_history_13 = models.IntegerField(primary_key=False, default=1)
    medical_history_14 = models.IntegerField(primary_key=False, default=1)
    medical_history_15 = models.CharField(max_length=100, default=1)
    medical_history_16 = models.IntegerField(primary_key=False, default=1)
    medical_history_17 = models.IntegerField(primary_key=False, default=1)
    medical_history_18 = models.IntegerField(primary_key=False, default=1)
    medical_history_19 = models.IntegerField(primary_key=False, default=1)
    medical_history_20 = models.IntegerField(primary_key=False, default=1)
    medical_history_21 = models.IntegerField(primary_key=False, default=1)
    medical_history_22 = models.IntegerField(primary_key=False, default=1)
    medical_history_23 = models.IntegerField(primary_key=False, default=1)
    medical_history_24 = models.CharField(max_length=100, default=1)
    medical_history_25 = models.IntegerField(primary_key=False, default=1)
    medical_history_26 = models.IntegerField(primary_key=False, default=1)
    medical_history_27 = models.IntegerField(primary_key=False, default=1)
    medical_history_28 = models.IntegerField(primary_key=False, default=1)
    medical_history_29 = models.IntegerField(primary_key=False, default=1)
    medical_history_30 = models.IntegerField(primary_key=False, default=1)
    medical_history_31 = models.IntegerField(primary_key=False, default=1)
    medical_history_32 = models.CharField(max_length=100, default=1)
    medical_history_33 = models.IntegerField(primary_key=False, default=1)
    medical_history_34 = models.IntegerField(primary_key=False, default=1)
    medical_history_35 = models.IntegerField(primary_key=False, default=1)
    medical_history_36 = models.IntegerField(primary_key=False, default=1)
    medical_history_37 = models.IntegerField(primary_key=False, default=1)
    medical_history_38 = models.IntegerField(primary_key=False, default=1)
    medical_history_39 = models.IntegerField(primary_key=False, default=1)
    medical_history_40 = models.IntegerField(primary_key=False, default=1)
    medical_history_41 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_1 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_2 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_3 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_4 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_5 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_6 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_7 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_8 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_9 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_10 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_11 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_12 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_13 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_14 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_15 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_16 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_17 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_18 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_19 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_20 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_21 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_22 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_23 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_24 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_25 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_26 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_27 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_28 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_29 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_30 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_31 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_32 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_33 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_34 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_35 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_36 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_37 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_38 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_39 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_40 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_41 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_42 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_43 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_44 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_45 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_46 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_47 = models.IntegerField(primary_key=False, default=1)
    medical_keyword_48 = models.IntegerField(primary_key=False, default=1)

    def __str__(self):
        return f"{self.id}"

    def get_absolute_url(self):
        return reverse("home", kwargs={})
