# Generated by Django 3.0.7 on 2020-06-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "application_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("age", models.CharField(default=None, max_length=100)),
                ("workclass", models.CharField(default=None, max_length=100)),
                ("fnlwgt", models.CharField(default=None, max_length=100)),
                ("education", models.CharField(default=None, max_length=100)),
                ("education_num", models.CharField(default=None, max_length=100)),
                ("marital_status", models.CharField(default=None, max_length=100)),
                ("occupation", models.CharField(default=None, max_length=100)),
                ("relationship", models.CharField(default=None, max_length=100)),
                ("race", models.CharField(default=None, max_length=100)),
                ("sex", models.CharField(default=None, max_length=100)),
                ("capital_gain", models.CharField(default=None, max_length=100)),
                ("capital_loss", models.CharField(default=None, max_length=100)),
                ("hours_per_week", models.CharField(default=None, max_length=100)),
                ("native_country", models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
