# Generated by Django 2.2.10 on 2020-08-29 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0002_auto_20200702_2036"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workclass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("worktype", models.CharField(default="Private", max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="income",
            name="workclass",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="income.Workclass"
            ),
        ),
    ]
