# Generated by Django 2.2.10 on 2020-08-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0003_auto_20200829_1454"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edu", models.CharField(default="Bachelors", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Marital_status",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ms", models.CharField(default="Never-married", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Native_country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nc", models.CharField(default="Canada", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Occupation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occ", models.CharField(default="Husband", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rc", models.CharField(default="White", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rel", models.CharField(default="Husband", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Sex",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Sx", models.CharField(default="Female", max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="income",
            name="education",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="income.Education"
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="marital_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="income.Marital_status"
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="native_country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="income.Native_country"
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="occupation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="income.Occupation"
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="income.Race"
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="relationship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="income.Relationship"
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="sex",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="income.Sex"
            ),
        ),
    ]
