# Generated by Django 2.2.10 on 2020-08-31 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0004_auto_20200829_1518"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sex",
            old_name="Sx",
            new_name="sx",
        ),
    ]
