# Generated by Django 2.2.10 on 2020-10-10 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0005_auto_20200831_2147"),
    ]

    operations = [
        migrations.RenameField(
            model_name="income",
            old_name="application_number",
            new_name="income_id",
        ),
        migrations.AlterField(
            model_name="income",
            name="marital_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="income.Marital_Status"
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="native_country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="income.Native_Country"
            ),
        ),
    ]
