# Generated by Django 2.2.6 on 2021-01-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0010_auto_20210101_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='marital_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.Marital_Status'),
        ),
        migrations.AlterField(
            model_name='income',
            name='native_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.Native_Country'),
        ),
    ]
